### ISSUE TITLE
Allow volume to be optional

### ISSUE THREAD

**Issue by lcarva** [openshift/csi-driver-shared-resource#110]
A regular `Secret` resource can be used as an optional volume:
```
volumes:            
- name: missing     
  secret:           
    secretName: missing
    optional: true  
```
If the secret does not exist, it does not prevent the Pod from being created. Any volumeMounts using the secret volume are mounted as an empty dir (or file if subpath is used). 

This is helpful in creating resources (Pods, Jobs, Deployments, etc) that work in different environments.

Is it possible to do the same for the `SharedSecret` resource?
